export const siteConfig = {
	title: "jason.wa的博客",
	shortTitle: "jason.wa",
	description: "记录日常生活、想法、脑洞、思考等",
	author: "jason.wa",
	lang: "zh-CN" as const,
	url: "https://mujizi.com",
	github: "https://github.com/jincaiw",
	repo: "https://github.com/jincaiw/walog",
	postsPerPage: 10,
	ogImage: "/og-default.png",
	footer: {
		since: 2024,
		name: "jason.wa",
	},
	nav: [
		{ text: "首页", href: "/" },
		{ text: "文章", href: "/blog" },
		{ text: "标签", href: "/tags" },
		{ text: "归档", href: "/archive" },
		{ text: "搜索", href: "/search" },
		{ text: "关于", href: "/about" },
	] as { text: string; href: string }[],
	giscus: {
		repo: "",
		repoId: "",
		category: "",
		categoryId: "",
	},
} as const;
